{% set name = "segno" %}
{% set version = "1.4.0" %}
{% set sha256 = "d6b4e4512fa5cb32d2f988584d20e2e4d1daa97587cd5421cb705da994f3d65b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.5
    - setuptools

test:
  imports:
    - segno

  commands:
    - segno -h

about:
  home: https://github.com/heuer/segno
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Segno is a QR Code and Micro QR Code encoder which has no further dependencies.
  description: |
    This package implements ISO/IEC 18004:2006(E) / ISO/IEC
    18004:2015(E) "QR Code bar code symbology specification" and
    produces Micro QR Codes and QR Codes with nearly no effort.
    Segno provides many serialization formats and could
    provide more serialization formats via a plugin architecture.
    Further, it provides several high level function to create QR
    Codes which encode contact data (MeCard, vCard) or WIFI
    configurations.
  doc_url: https://segno.readthedocs.io/
  dev_url: https://github.com/heuer/segno

extra:
  recipe-maintainers:
    - bryanwweber
